print(math.type(3))
print(math.type(3.0))

print(math.floor(3.3))
print(math.floor(-3.3))
print(math.ceil(3.3))
print(math.ceil(-3.3))
print(math.modf(3.3))
print(math.modf(-3.3))
print(math.floor(2^70))

print(math.tointeger(-258.0))
print(math.tointeger(2^30))
print(math.tointeger(5.01))
print(math.tointeger(2^64))